### ISSUE TITLE
failure when call returns >20K observations

### ISSUE THREAD

**Issue by philippi** [ropensci/rinat#14]
Calls that return more than 20K observations fail with "Error in data$status_code : object of type 'closure' is not subsettable".  Example (Santa Monica Mountains NRA including BioBlitz observations):
`iNatHits <- get_inat_obs(bounds=c(37.43380, -122.93986,   38.22174, -122.27673), 
                                        maxresults=1000000)`
According to  [http://www.inaturalist.org/pages/api+reference#get-observations](http://www.inaturalist.org/pages/api+reference#get-observations) , the current iNaturalist API appears to stop after 100 pages (200*100=20k observations) without authentication.  
The simple fix is to change the threshold in the error trapping in lines 128:129 to be 20000.  

I see 2 approaches to the broader solution. 
First, a separate function get_inat_Nobs could be built from this code down to line 124, then returning total_res.  The user could use that ping to determine if they need to split their request by year, month, etc., to get each chunk under 20K.  [I would document this on the same page as get_inat_obs, with the difference noted in Value, but that might not be your style.]  {The above call has total_res == 107544 via this approach.}

The second approach would be to support credentials & authentication as in rgbif.  I don't know how difficult this would be to implement.  It would respect the intent of the iNaturalist limit to let them know who is scraping large amounts of data.  Also, it might allow for the iNaturalist API to vend unobscured coordinates when authentication credentials match their internal project-based permissions.  My use case is that NPS is using iNaturalist for all of our BioBlitzes, and may adopt it for all of our species observation data.  That will make our data available to the wider community, albeit with obscured coordinates for sensitive species.  If we can pass credentials through to get our own data with full coordinates, I can coerce many more NPS folks to use iNaturalist and make their observations visible to the public.

**Comment by sckott** [comment]
@emhart do you have time for this or should I?

**Comment by philippi** [comment]
Another minimalist option would be to add a parameter like countOnly=False, then 
```
125  if (countOnly) {
            return(total_res)
        } else {
            ...
155.5  }
```
I don't know how you feel about a function returning different classes of objects depending on parameter values, versus duplicating large blocks of code in separate functions.

I am in no rush on this, as I've made my own local version of get_inat_Nobs to return the number of hits.   I also have a block of code that checks if the overall call returns >20K, and if so, starts splitting recursively: by year, then by month for years with >20K, then day for month/years with >20k.  I'd be willing to contribute that part, but it is a bit abusive and against the spirit of what iNaturalist asks for in their API.  Unfortunately, I'm not competent to code the authentication part for iNaturalist's API.

**Comment by emhart** [comment]
I'm happy to implement it @sckott I guess the question is what's the best approach?  My thinking is that we should implement the authentication.  What do you think?

**Comment by philippi** [comment]
As of this evening I suggest not looking at authentication for a few months until their JSON API has authentication.

I contacted iNaturalist to let them know I was hitting their serve at night. Their response:

> "We hadn't even noticed any hammering, so I guess you weren't hammering
> all that hard! Regarding auth, the current Node API would definitely
> be more performative, but it doesn't have any auth at present, so if
> you're going to work on auth in rinat, best to focus on the
> traditional API.
> 
> That said, we are hoping to roll out JSON web token auth for the node
> API some time soon, though we had no plans for privileged coordinate
> access for authenticated GET requests. I take it this would be
> something you'd want? Might also help to know why exactly you want to
> make authenticated requests if you're just pulling down data."
> 
> -ken-ichi

So, perhaps changing the limit in line 128 to 20000, changing the wording of the error message in line 129 for the immediate issue, then either creating a new get_inat_Nobs function or add a countOnly parameter to get_inat_obs.

**Comment by sckott** [comment]
The above solution eems reasonable

**Comment by emhart** [comment]
@philippi I did a quick change on the line.  Not sure I see the logic of getting a separate count fxn if the current version just throws a suggestive error.
