### ISSUE TITLE
csv data type is apparently not available for observations route anymore

### ISSUE THREAD

**Issue by sckott** [ropensci/rinat#16]

**Comment by emhart** [comment]
@sckott could you provide some clarity on this?  I'm just trying to figure out what the issue is exactly.

**Comment by sckott** [comment]
Sorry, been a while. I think it just didn't work for me back in June when I opened this.  Maybe its fine now?

**Comment by emhart** [comment]
Pulling data down by CSV still seems to be working is all, but I'm not sure what you meant by "route" .

**Comment by sckott** [comment]
ah, just the API route, like base URL + `/observations`

**Comment by kueda** [comment]
http://www.inaturalist.org/observations.csv works for me, though I'd advise you guys use the JSON responses to get the most data possible.

**Comment by emhart** [comment]
@kueda Is there more data that's returned via JSON vs. CSV?  Either way this sounds like a good idea, but  I think I'm going to tag this release with a bunch of bug fixes and save that transition for a bigger release.

**Comment by kueda** [comment]
Definitely more data in the JSON responses, both from our Rails-based API and our Node-based API.

**Comment by stragu** [comment]
Closing this for now as it seems the original issues was a temporary unavailability of CSV data via API. Might open a new issue about transitioning to JSON.
