### ISSUE TITLE
Pull in from guides?

### ISSUE THREAD

**Issue by bomeara** [ropensci/rinat#21]
iNaturalist now has guides. For example, [Plants of Mueller State Park](https://www.inaturalist.org/guides/5481). There doesn't seem to be an API to them or a way to get them from `rinat`. Not sure if I'm missing something, but if not, this could be a useful feature.

**Comment by sckott** [comment]
thanks @bomeara 

@kueda is there an API endpoint for the guides?

**Comment by bomeara** [comment]
And just to give a little context, I'm working with the phylotastic project -- a system to go from a list of names to a phylogenetic tree (ideally, a chronogram). One thing we've talked about is a phyloguide: for a list of all the species (in a national park, in a movie (Finding Nemo), etc.) return a phylogeny of all the taxa and maybe things like links to EOL, images, maps, etc. This has overlap with iNaturalist guides, so we could maybe build on them, or offer to help incorporate our tools within iNaturalist.

**Comment by sckott** [comment]
Nice, thanks @bomeara 

Building for a mobile/web app or twitter bot or something else?

**Comment by kueda** [comment]
There's an undocumented API, but it's undocumented for a reason: guides
were kind of a dead end for us, far less rich in novel content than we had
hoped, so we're not that excited about doing any novel development around
them or promoting their use.

You might instead consider using our observations API to create such custom
phylogenies for place / time / taxon / user combinations.

**Comment by bomeara** [comment]
Thanks, @kueda. Makes sense -- and it's great that the project adapts to what is working best.

@sckott: our main target for the phyloguides is teaching. "Ok, class, we're going to Baxter State Park -- here are the plants we might see and how they're related."
