### ISSUE TITLE
get_inat_obs_user error with certain users

### ISSUE THREAD

**Issue by fischhoff** [ropensci/rinat#23]
Update: This error happens with users with many (>10K) records, though some have <20K, so I don't know that this is a repeat of issue #14. 

I get an error with get_inat_obs_user with some users, for example: 
>temp = get_inat_obs_user("anudibranchmom",
                           maxresults = 100000)
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

These are some other users for which I get the same error:
charlie
annikaml
berkshirenaturalist
rcurtis
erikamitchell

Thanks!

**Comment by vijaybarve** [comment]
The error could not be reproduced, so may be recent version does not have this issue.

**Comment by fischhoff** [comment]
Thank you for following up!
Ilya

**Comment by stragu** [comment]
Just tested again, and can confirm that it works as expected: I don't get the error.
Might close this now, unless you still see that, @fischhoff ?

**Comment by fischhoff** [comment]
Hi Stéphane, thanks for the update! Feel free to close.
Ilya
