### ISSUE TITLE
get_inat_obs_project(), error in downloading data from iNaturalist collection and umbrella projects

### ISSUE THREAD

**Issue by enjieli** [ropensci/rinat#28]
I am encountering an error when using get_inat_obs_project() function to download data from iNaturalist Collection projects and Umbrella Projects. The get_inat_obs_project() works fine for traditional projects. It seems like this bug is related to the new projects types and how the data are formatted differently in the iNaturalist API. This is the error I got: `Error in read.table(file = file, header = header, sep = sep, quote = quote,  :   no lines available in input`.

See example codes here:

`rm(list= ls())`
`library(rinat)`
`###Traditional Projects, can read in info and  download data####`
`df <- get_inat_obs_project("slime", type = "info", raw = F)`
`df <- get_inat_obs_project("slime", type = "observations", raw = F)`

`df <- get_inat_obs_project("rascals", type = "info", raw = F)`
`df <- get_inat_obs_project("rascals", type = "observations", raw = F)`

`###Umbrella Projects, can read in info, but cannot download data####`
`df <- get_inat_obs_project("city-nature-challenge-2018", type = "info", raw = F)`
`df <- get_inat_obs_project("city-nature-challenge-2018", type = "observations", raw = F)`

`df <- get_inat_obs_project("city-nature-challenge-2019", type = "info", raw = F)`
`df <- get_inat_obs_project("city-nature-challenge-2019", type = "observations", raw = F)`

`###Collection Projects, can read in info, but cannot download data####`
`df <- get_inat_obs_project("global-amphibian-bioblitz", type = "info", raw = F)`
`df <- get_inat_obs_project("global-amphibian-bioblitz", type = "observations", raw = F)`

`df <- get_inat_obs_project("ucla-campus-biodiversity", type = "info", raw = F)`
`df <- get_inat_obs_project("ucla-campus-biodiversity", type = "observations", raw = F)`

**Comment by danilovcorrea** [comment]
Hi developers,

Confirming the error related by enjieli. The script is not working with collection and umbrella project. There is an perspective to update "rinat" to work with new project types? It would be nice to have "rinat" working again.
Thanks for appreciate this comment.

**Comment by Vojczech** [comment]
It seems that `get_inat_obs_project()` still does not work. Hopefully it will be fixed soon.

**Comment by Martin-Jung** [comment]
I have this error occuring for one of our projects. Anything that can be done?
To reproduce:

```
install.packages('rinat')
library(rinat)
obs <- get_inat_obs_project("flowering-plants-of-ethiopia", type = "observations", raw = F)

```
> 1170  Records
>0-100Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
> no lines available in input
