### ISSUE TITLE
[Bug] rbind error in get_inat_obs_project()

### ISSUE THREAD

**Issue by Martin-Jung** [ropensci/rinat#37]
Followup from this issue #28 
While downloading and reading from the table works with the current development build, there is still an rbind error at the end.

```
library(rinat)
obs <- get_inat_obs_project("flowering-plants-of-ethiopia", type = "observations", raw = T)
```
>1170  Records
>0-200-400-600-800-1000-1200Error in rbind(deparse.level, ...) : 
> numbers of columns of arguments do not match

**Comment by emhart** [comment]
Hi Martin.  I have merged your fix, which I believe also fixes what @sastoudt also needed to fix.

**Comment by sastoudt** [comment]
Thanks Martin!
