### ISSUE TITLE
get_inat_obs_project: "Not found"

### ISSUE THREAD

**Issue by bjornekstrom** [ropensci/rinat#43]
`get_inat_obs_project` does not return any results, even in developer version of rinat.

```{r}
get_inat_obs_project(354, type = "observations")
```

gives

```{r}
1362  Records
0-200-400-600-800-1000-1200-1400[1] "Not found"
```

**Comment by vijaybarve** [comment]
Not able to replicate. @bjornekstrom can you please provide session info and confirm the error persists.

**Comment by bjornekstrom** [comment]
@vijaybarve I tried this again today and now it works. Closing this issue.
