### ISSUE TITLE
Error in get_inat_obs : unused argument place_id

### ISSUE THREAD

**Issue by stdataanalytics** [ropensci/rinat#51]
Hi all,
I'm using the function `rinat::get_inat_obs()`.
Reading the [doc](https://cran.r-project.org/web/packages/rinat/rinat.pdf) the parameters `place_id` is supported, but when I launch:

```
get_inat_obs( query = "Lacerta Bilineata"
            , year = "2020"
            , maxresults = 10
            , place_id = 8670) 
```

I got:

`Error in get_inat_obs(query = "Lacerta Bilineata", year = "2020", maxresults = 10,  : 
  unused argument (place_id = 8670)`

**EDIT**:
I am using` rinat_0.1.5` and `R 4.0.4`

Am I doing wrong something?

Thanks

**Comment by stdataanalytics** [comment]
updated the package, sorry for the sloppy issue.

**Comment by stragu** [comment]
No worries, @stdataanalytics ! Glad it was solved by an update, and thanks for being willing to report a reproducible issue in the first place! :smile:
